"""Online detection runtime — prompt in, per-checkpoint verdict out.

This is the deployed loop of the detection design (§2.2 / §5), in one process:

    prompt ──▶ HF greedy generation (eager attention)
            ──▶ at total length L ∈ {256,512,1024,2048,4096}: one full-prefix
                forward that accumulates the head-averaged, layer-averaged
                (L,L) attention matrix
            ──▶ attn_consistency_independent / prompt_mean_fraction per gen token
            ──▶ running (cons_ind_mean, pmf_slope, log L) ──▶ classifier
            ──▶ τ_prob gate; first confident attack call = trigger (early stop)

Fidelity rules (why this is comparable to the offline pipeline, not merely
similar to it):

  - the attention matrix is produced by the SAME hook as
    ``extract_layer_avg_attention`` (head mean → layer mean, eager attention);
  - the two metrics are computed by importing the SAME functions from
    ``compute_step_trajectory``, over the same per-position token strings
    (``tokenizer.decode([id])``);
  - the features and the τ gate come from ``detector.py``, shared with
    ``replay_checkpoints.py``.

The one thing that genuinely differs from training is the *text*: training
trajectories were generated by vLLM and loop-truncated (kept_iters=5), while
here the stream is live. Measuring that gap is the point of
``--dump-metrics`` (per-token arrays are saved so an online-vs-offline
comparison can be run afterwards on the same prompt).

Runs in the ``Recur`` env (torch + transformers, no sklearn) — pass the JSON
export of the classifier produced by ``detector.py --export``.

    PYTHONPATH=. /root/miniconda3/envs/Recur/bin/python \
        -m recur_code.src.detection.detection_runtime \
        --model $RC_MODELS_ROOT/DeepSeek-R1-Distill-Llama-8B \
        --detector recur_code/exp/detection_dataset/models/loop_detector_llama8b_4class_method2.json \
        --gpu 1 --prompt "..."
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "recur_code" / "src" / "detection"))

from detector import (CHECKPOINTS, DEFAULT_TAU_PROB, MIN_GEN_FOR_SLOPE,  # noqa: E402
                      DetectionTrace, Detector, checkpoint_index, load_detector)

THINK_CLOSE = "</think>"


def _load_metric_fns():
    """The two metric implementations, imported (not copied) from the offline
    pipeline so online and offline can never silently diverge."""
    from recur_code.visualization.reasoning_chat.compute_step_trajectory import (
        _compute_per_token_consistency_independent, _compute_per_token_ratios,
    )
    return _compute_per_token_consistency_independent, _compute_per_token_ratios


class OnlineLoopDetector:
    """Generate under a target LLM while probing it at the fixed checkpoints."""

    def __init__(self, model_path: str, detector_path: str, *,
                 gpu: str = "0", checkpoints: list[int] | None = None,
                 tau_prob: float = DEFAULT_TAU_PROB, max_new_tokens: int = 4096,
                 temperature: float = 0.0, head_agg: str = "mean",
                 stop_on_attack: bool = True, dtype: str = "bfloat16",
                 stop_at_think_close: bool = False):
        os.environ.setdefault("CUDA_VISIBLE_DEVICES", gpu)
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer

        self.torch = torch
        self.checkpoints = list(checkpoints or CHECKPOINTS)
        self.tau_prob = tau_prob
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.head_agg = head_agg
        self.stop_on_attack = stop_on_attack
        self.det: Detector = load_detector(detector_path)
        self._cons_fn, self._ratio_fn = _load_metric_fns()

        print(f"[runtime] loading {model_path} (eager attention, {dtype}) ...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_path)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_path,
            torch_dtype=getattr(torch, dtype),
            attn_implementation="eager",   # required: sdpa/flash return no weights
            device_map="cuda:0",
        )
        self.model.eval()
        self.n_layers = self.model.config.num_hidden_layers

        # Generation stops at EOS only. `</think>` is deliberately NOT a stop
        # token: repetitive_string degenerates in the ANSWER, after </think>
        # (see _common.loop_check_for_category), so cutting there would hide the
        # very behaviour we detect — and it is also what the offline
        # repetitive_string attention caches were extracted over (full text).
        think_ids = self.tokenizer(THINK_CLOSE, add_special_tokens=False).input_ids
        self.think_close_id = think_ids[0] if len(think_ids) == 1 else None
        self.eos_ids = [self.tokenizer.eos_token_id]
        if stop_at_think_close and self.think_close_id is not None:
            self.eos_ids.append(self.think_close_id)
        print(f"[runtime] layers={self.n_layers} "
              f"heads={self.model.config.num_attention_heads} "
              f"stop_ids={self.eos_ids} detector={Path(detector_path).name}")

    # ---------------------------------------------------------------- attention
    def _layer_avg_attention(self, input_ids) -> np.ndarray:
        """One full-prefix forward → (L,L) head-avg + layer-avg matrix (fp32).

        Same accumulate-and-drop hook as ``extract_layer_avg_attention``: each
        layer's weights are head-aggregated on GPU, folded into a CPU fp32 sum,
        and then nulled so HF never holds n_layers matrices at once.
        """
        from recur_code.src.analysis.extract_layer_avg_attention import (
            _make_accumulate_hook,
        )
        from recur_code.src.analysis.extract_step_attention import get_decoder_layers

        state: dict[str, Any] = {"sum": None, "seen": set()}
        layers = get_decoder_layers(self.model)
        handles = [layers[i].self_attn.register_forward_hook(
            _make_accumulate_hook(state, i, self.head_agg))
            for i in range(self.n_layers)]
        try:
            with self.torch.no_grad():
                self.model(input_ids, output_attentions=True)
        finally:
            for h in handles:
                h.remove()
        self.torch.cuda.empty_cache()
        if len(state["seen"]) != self.n_layers or state["sum"] is None:
            raise RuntimeError(
                f"hook captured {len(state['seen'])}/{self.n_layers} layers — "
                f"check attn_implementation='eager' and the transformers version")
        return state["sum"] / float(self.n_layers)

    # ---------------------------------------------------------------- generation
    def _generate_to(self, ids, target_len: int):
        """Greedy-continue from `ids` until total length `target_len` or a stop
        token. Returns (ids, stopped). Each segment re-prefills — 5 extra
        prefills over a run, negligible beside decoding thousands of tokens."""
        need = target_len - ids.shape[1]
        if need <= 0:
            return ids, False
        kw = dict(max_new_tokens=need, use_cache=True,
                  eos_token_id=self.eos_ids,
                  pad_token_id=self.tokenizer.eos_token_id)
        if self.temperature and self.temperature > 0:
            kw.update(do_sample=True, temperature=self.temperature)
        else:
            kw.update(do_sample=False)
        with self.torch.no_grad():
            out = self.model.generate(ids, **kw)
        stopped = bool(out[0, -1].item() in self.eos_ids)
        return out, stopped

    def _render_prompt_ids(self, prompt: str):
        """Render a user prompt exactly as both runtime modes expect."""
        prompt_text = self.tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False, add_generation_prompt=True)
        return self.tokenizer(prompt_text, return_tensors="pt",
                              add_special_tokens=False).input_ids.to(self.model.device)

    def run_baseline(self, prompt: str) -> dict[str, Any]:
        """Generate with this runtime's model but without any detector work.

        This is deliberately part of :class:`OnlineLoopDetector` rather than a
        separate vLLM path: a latency comparison must hold the checkpoint,
        tokenizer, chat template, dtype, device and decode parameters fixed.
        """
        ids = self._render_prompt_ids(prompt)
        prompt_len = int(ids.shape[1])
        self.torch.cuda.synchronize()
        t0 = time.perf_counter()
        ids, stopped = self._generate_to(ids, prompt_len + self.max_new_tokens)
        self.torch.cuda.synchronize()
        seconds = time.perf_counter() - t0
        gen_tokens = int(ids.shape[1] - prompt_len)
        return {
            "prompt_len": prompt_len,
            "gen_tokens": gen_tokens,
            "seq_len": int(ids.shape[1]),
            "stopped_naturally": bool(stopped),
            "hit_cap": bool(gen_tokens >= self.max_new_tokens),
            "wall_seconds": seconds,
        }

    # ---------------------------------------------------------------- main loop
    def run(self, prompt: str, meta: dict[str, Any] | None = None,
            dump_metrics: bool = False) -> dict[str, Any]:
        tok = self.tokenizer
        ids = self._render_prompt_ids(prompt)
        prompt_len = ids.shape[1]
        cap = prompt_len + self.max_new_tokens

        trace = DetectionTrace()
        t_gen = t_attn = t_metric = 0.0
        stopped = False
        cons = pmf = None
        probe_log = []

        self.torch.cuda.synchronize()
        t_wall = time.perf_counter()
        for L in self.checkpoints:
            if L > cap:
                break
            if L - prompt_len - 1 < MIN_GEN_FOR_SLOPE - 1:
                # The probe position falls inside the prompt (long attack
                # prompts routinely pass 512 tokens) — nothing to measure yet.
                continue
            if ids.shape[1] < L:
                if stopped:
                    break                      # ended naturally before this probe
                t0 = time.time()
                ids, stopped = self._generate_to(ids, L)
                t_gen += time.time() - t0
                if ids.shape[1] < L:
                    break                      # stop token fired before reaching L

            t0 = time.time()
            attn = self._layer_avg_attention(ids[:, :L])
            t_attn += time.time() - t0

            t0 = time.time()
            flat = ids[0, :L].tolist()
            tokens = [tok.decode([i], skip_special_tokens=False) for i in flat]
            cons, _ = self._cons_fn(attn, prompt_len, tokens, threshold=0.9)
            pmf = self._ratio_fn(attn, prompt_len)[3]
            t_metric += time.time() - t0
            del attn

            i = checkpoint_index(L, prompt_len, int(pmf.size))
            if i is None:
                continue
            call = trace.add(self.det, L, i, cons, pmf, prompt_len, self.tau_prob)
            if call is None:
                continue
            probe_log.append(call)
            print(f"    [L={L:>5}] cons_ind={call.cons_ind_mean:.3f} "
                  f"pmf_slope={call.pmf_slope:+.2e} -> {call.pred:<20} "
                  f"p={call.prob:.3f} {'DECIDE' if call.decided else 'uncertain'}"
                  f"{'  ** ATTACK TRIGGER **' if call.is_attack_call else ''}")
            if call.is_attack_call and self.stop_on_attack:
                break

        # A detector normally has no reason to end decoding after its final
        # checkpoint.  Continuing here also lets latency benchmarks compare
        # identical total-length caps with and without online detection.
        if not stopped and not (trace.trigger is not None and self.stop_on_attack):
            t0 = time.time()
            ids, stopped = self._generate_to(ids, cap)
            t_gen += time.time() - t0

        self.torch.cuda.synchronize()
        wall_seconds = time.perf_counter() - t_wall

        gen_ids = ids[0, prompt_len:].tolist()
        text = tok.decode(gen_ids, skip_special_tokens=True)
        thinking = text.split(THINK_CLOSE)[0]
        result: dict[str, Any] = {
            **(meta or {}),
            "prompt": prompt,
            "prompt_len": int(prompt_len),
            "gen_tokens": int(len(gen_ids)),
            "seq_len": int(ids.shape[1]),
            "stopped_naturally": bool(stopped),
            "hit_cap": bool(len(gen_ids) >= self.max_new_tokens),
            "thinking_tokens": int(len(tok(thinking, add_special_tokens=False).input_ids)),
            "thinking": thinking,
            "full_text": text,
            "wall_seconds": wall_seconds,
            "seconds": {"generate": round(t_gen, 2), "attention": round(t_attn, 2),
                        "metrics": round(t_metric, 2)},
            **trace.as_dict(),
        }
        if dump_metrics and cons is not None:
            result["metrics_upto"] = int(pmf.size)
            result["cons_ind"] = [None if not np.isfinite(x) else round(float(x), 6)
                                  for x in cons]
            result["pmf"] = [None if not np.isfinite(x) else round(float(x), 6)
                             for x in pmf]
        return result


def main() -> int:
    import argparse
    import json

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--model", required=True)
    ap.add_argument("--detector", required=True,
                    help=".json export (Recur env) or .joblib (needs sklearn)")
    ap.add_argument("--prompt", required=True)
    ap.add_argument("--gpu", default="0")
    ap.add_argument("--tau-prob", type=float, default=DEFAULT_TAU_PROB)
    ap.add_argument("--max-new-tokens", type=int, default=4096)
    ap.add_argument("--temperature", type=float, default=0.0)
    ap.add_argument("--no-early-stop", action="store_true")
    ap.add_argument("--stop-at-think-close", action="store_true",
                    help="also stop generating at </think> (hides "
                         "repetitive_string, which loops in the answer)")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()

    det = OnlineLoopDetector(
        a.model, a.detector, gpu=a.gpu, tau_prob=a.tau_prob,
        max_new_tokens=a.max_new_tokens, temperature=a.temperature,
        stop_on_attack=not a.no_early_stop,
        stop_at_think_close=a.stop_at_think_close)
    r = det.run(a.prompt)
    print(f"\n[runtime] verdict={r['verdict']} trigger_L={r['trigger_L']} "
          f"gen_tokens={r['gen_tokens']} seconds={r['seconds']}")
    if a.out:
        os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
        with open(a.out, "w") as f:
            json.dump(r, f, ensure_ascii=False, indent=1)
        print(f"[runtime] wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
